name: Auto Update NPC

on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: |
        PROJECT_LATEST_TAG=$(wget -q -O- "https://api.github.com/repos/${GITHUB_REPOSITORY}/tags" | grep '"name":' | sed -E 's#.*"(.+)".*#\1#' | head -n1)
        NPC_LATEST_TAG=$(wget -q -O- https://api.github.com/repos/cnlh/nps/releases/latest | grep '"tag_name":' | sed -E 's#.*"v(.+)".*#\1#' | head -n1)

        echo "npc: $NPC_LATEST_TAG"
        echo "docker-npc: $PROJECT_LATEST_TAG"

        if [ $PROJECT_LATEST_TAG != $NPC_LATEST_TAG ]; then
          git config user.name "Bot"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          sed -i "s#NPC_VERSION=.*#NPC_VERSION=$NPC_LATEST_TAG#" Dockerfile
          git add Dockerfile
          git commit -m "feat: 升级 npc 版本 [$NPC_LATEST_TAG]"
          git tag -a "$NPC_LATEST_TAG" -m "npc v$NPC_LATEST_TAG"
          git push -u origin master --follow-tags
        fi
